# Generated by Django 5.1.3 on 2024-11-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='material',
            name='article',
            field=models.IntegerField(verbose_name='Код материала'),
        ),
    ]
